#!/bin/bash
set -e

SCRIPT_PATH=$(dirname $(readlink -f "${0}"))
source "${SCRIPT_PATH}/aws-functions.sh"

usage() {
  echo "Usage: $(basename $0) [-h|--help] [-d|--debug]"
  echo ""
  echo "Lists all AWS profiles defined in ~/.aws/config"
  echo ""
  echo "Options:"
  echo "  -h, --help          Show this help message"
  echo "  -d, --debug         Debug mode, outputs all commands (or set DEBUG=1)"
  echo ""
  echo "Environment Variables:"
  echo "  AWS_CONFIG_FILE     Override AWS config file location (default: ~/.aws/config)"
  echo ""
  echo "Examples:"
  echo "  $(basename $0)                           # List all profiles"
  echo "  $(basename $0) | grep prod               # Filter profiles"
  echo "  AWS_CONFIG_FILE=~/.aws/config2 $(basename $0)  # Use different config file"
}

while [[ $# -gt 0 ]]; do
  case $1 in
  -h | --help)
    usage
    shift
    exit 0
    ;;
  -d | --debug)
    set_debug
    shift
    exit 0
    ;;
  *)
    log_error "Unknown option $1"
    usage
    exit 1
    ;;
  esac
done

[[ -r "${AWS_CONFIG_FILE:-$HOME/.aws/config}" ]] || exit 1
sed -n -e 's/^\[profile[[:space:]]\(.*\)\]$/\1/p' ${AWS_CONFIG_FILE}
# grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} --color=never -Eo '\[.*\]' "${AWS_CONFIG_FILE:-$HOME/.aws/config}" | sed -E 's/^[[:space:]]*\[(profile)?[[:space:]]*([-_[:alnum:]\.@]+)\][[:space:]]*$/\2/g'
