#!/bin/bash
set -e

SCRIPT_PATH=$(dirname $(readlink -f "${0}"))
source "${SCRIPT_PATH}/aws-functions.sh"

usage() {
  echo "Usage: $(basename $0) [-p|--profile AWS Profile Name] [-r|--region AWS Region Name]"
  echo ""
  echo "Options:"
  echo "  -p, --profile NAME   AWS Profile Name"
  echo "  -r, --region NAME    AWS Region Name"
  echo "  -h, --help           Show this help message"
  echo ""
  echo "Examples:"
  echo "  $(basename $0)                                    # Interactive mode (requires fzf)"
  echo "  $(basename $0) --profile prod --region us-east-1"
  echo "  $(basename $0) --profile dev"
}

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -r|--region)
      AWS_REGION="$2"
      shift # past argument
      shift # past value
      ;;
    -p|--profile)
      AWS_PROFILE="$2"
      shift # past argument
      shift # past value
      ;;
    -h|--help)
      usage
      shift
      exit 0
      ;;
    *)
      echo "Unknown option $1"
      usage
      exit 1
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters


[[ -z ${AWS_PROFILE} ]] && {
  if ${IS_FZF}; then
    choose_profile_interactive
  else
    echo "AWS Profile to use not defined!"; exit 1;
  fi
}

check_aws_profile
check_aws_region

log_ok "AWS Profile: ${AWS_PROFILE}"
log_ok "AWS Region: ${AWS_REGION}"

AWS_ECR_REGISTRY_ID=$(aws ecr describe-registry --profile ${AWS_PROFILE} | jq -r '.registryId')
AWS_ECR_REGISTRY_ENDPOINT="${AWS_ECR_REGISTRY_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
log_info "Getting docker creds for ${AWS_ECR_REGISTRY_ENDPOINT}"

aws ecr get-login-password --region ${AWS_REGION} --profile ${AWS_PROFILE} | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ENDPOINT}

